# Export Invoice Summary Report Data Extraction

## 1. Load and Balance

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [2]:
df_wo = pd.read_excel("Data/EIS_WO.xlsx")
df_sw = pd.read_excel("Data/EIS_SW.xlsx")

In [3]:
print("Shape of EIS_WO:", df_wo.shape)
print("Shape of EIS_SW:", df_sw.shape)

Shape of EIS_WO: (45066, 43)
Shape of EIS_SW: (1452, 43)

In [4]:
df = pd.concat([df_wo,df_sw], ignore_index=False)
df.sample(5)

,LC Factory,LC/SC No,LC/SC Value,LC/SC Quantity,LC/SC Payment Term,Invoice No,Invoice Date,EXP No,EXP Date,Buyer,...,Bank Submit Date,Expected Realize Date,Is FDBC,Bank Name,Shipping Mode,Invoice Status,Realize NO,Realize Date,Realize Value,Is Realize
20607,MGSL,MGSL/H&M-MENS-S.0,7963192.82,1672612,EOM+63,2412510,25-Aug-2024,00000042-017969-2024,26-Aug-2024,H&M,...,05-Sep-2024,NaN,Yes,ABL,Sea,Incentive Pending,DR-09-24-015,08-Sep-2024,361.62,Yes
32803,MGSL,MGSL/H&M-Mens DBL-S.02,12435079.87,3145397,EOM 63,2505876,24-Apr-2025,00001689-012616-2025,24-Apr-2025,H&M,...,08-Jul-2025,NaN,Yes,DBBL,Sea,Incentive Pending,DR-07-25-014,08-Jul-2025,281.16,Yes
6091,MGSL,MGSL/ROBIN OXFORD SHIRT SEASON-9,2038510.93,432934,EOM 63,2316376,18-Nov-2023,042/017845/23,18-Nov-2023,H&M,...,10-Dec-2023,NaN,Yes,ABL,Sea,Incentive Pending,DR-12-23-037,10-Dec-2023,132.72,Yes
29459,MGSL,MGSL/H&M Kids DBBL-S.0,7767885.39,2760068,EOM+63,2502479,09-Feb-2025,00001689-005193-2025,09-Feb-2025,H&M,...,08-May-2025,NaN,Yes,DBBL,Sea,Incentive Pending,DR-05-25-030,08-May-2025,380.80,Yes
27364,MGSL,MGSL/H&M-Mens DBL-S.0,11664021.68,2755553,EOM+63,2500362,05-Jan-2025,00001689-000792-2025,05-Jan-2025,H&M,...,27-Feb-2025,NaN,Yes,DBBL,Sea,Incentive Pending,DR-02-25-049,27-Feb-2025,4013.80,Yes

In [5]:
## shuffle the data frame
df = df.sample(frac=1, random_state = 42)
df.head(4)

,LC Factory,LC/SC No,LC/SC Value,LC/SC Quantity,LC/SC Payment Term,Invoice No,Invoice Date,EXP No,EXP Date,Buyer,...,Bank Submit Date,Expected Realize Date,Is FDBC,Bank Name,Shipping Mode,Invoice Status,Realize NO,Realize Date,Realize Value,Is Realize
198,MFSL,LI23J01319,188098.72,23121,60 Days,2317023,28-Nov-2023,2155/007418/23,29-Nov-2023,DK Company,...,13-Dec-2023,NaN,Yes,PRM,Sea,Incentive Pending,DR-03-24-020,06-Mar-2024,43222.40,Yes
19891,MGSL,MGSL/H&M-Mens DBL-S.0,11664021.68,2755553,EOM+63,2411748,08-Aug-2024,00001689-013710-2024,08-Aug-2024,H&M,...,04-Sep-2024,NaN,Yes,DBBL,Sea,Incentive Pending,DR-09-24-005,04-Sep-2024,13136.22,Yes
10565,MGSL,MGSL/Robin Oxford Shirt S. 8,2622975.35,501569,60 Days,MGSL/23/3143,04-May-2023,005638,04-May-2023,H&M,...,07-Jun-2023,NaN,Yes,ABL,Sea,Incentive Pending,DR-06-23-004,07-Jun-2023,13977.80,Yes
41062,MGSL,MGSL/H&M Kids S2,8421788.29,2571162,EOM 63,2600548,11-Jan-2026,00001689-001143-2026,11-Jan-2026,H&M,...,12-Mar-2026,15-Mar-2026,Yes,DBBL,Sea,Incentive Pending,DR-03-26-027,11-Mar-2026,298.77,Yes

In [6]:
df.isnull().sum()

LC Factory                   0
LC/SC No                     0
LC/SC Value                  0
LC/SC Quantity               0
LC/SC Payment Term           9
Invoice No                   0
Invoice Date                 0
EXP No                      57
EXP Date                     0
Buyer                        0
PO No                       11
Merchandiser                 0
Destination No               3
Invoice Qty                  0
Carton Qty                1113
Invoice Value                0
Discount                     0
Commission                   0
ExfactoryDate              111
Ex Factory No              119
Ex Factory                 119
On Board Date              670
Payment Due Date           683
OnBoardDiff                687
Feeder Vessel No         46518
Mother Vessel No         18623
Shipping Bill No          7816
Shipping Bill Date        7817
BL No                     2712
BL Date                   2837
FCR No                    2993
FCR Date                  3055
Bank Ref No               2814
Bank Submit Date          2814
Expected Realize Date    40468
Is FDBC                      0
Bank Name                    1
Shipping Mode                0
Invoice Status               0
Realize NO                2952
Realize Date              2952
Realize Value             2953
Is Realize                   0
dtype: int64

-- This data frame has multiple parameter null value . So, Keep it BRAIN

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 46518 entries, 198 to 15795
Data columns (total 43 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   LC Factory             46518 non-null  object
 1   LC/SC No               46518 non-null  object
 2   LC/SC Value            46518 non-null  float64
 3   LC/SC Quantity         46518 non-null  int64
 4   LC/SC Payment Term     46509 non-null  object
 5   Invoice No             46518 non-null  object
 6   Invoice Date           46518 non-null  object
 7   EXP No                 46461 non-null  object
 8   EXP Date               46518 non-null  object
 9   Buyer                  46518 non-null  object
 10  PO No                  46507 non-null  object
 11  Merchandiser           46518 non-null  object
 12  Destination No         46515 non-null  object
 13  Invoice Qty            46518 non-null  int64
 14  Carton Qty             45405 non-null  float64
 15  Invoice Value          46518 non-null  float64
 16  Discount               46518 non-null  float64
 17  Commission             46518 non-null  int64
 18  ExfactoryDate          46407 non-null  object
 19  Ex Factory No          46399 non-null  object
 20  Ex Factory             46399 non-null  object
 21  On Board Date          45848 non-null  object
 22  Payment Due Date       45835 non-null  object
 23  OnBoardDiff            45831 non-null  float64
 24  Feeder Vessel No       0 non-null      float64
 25  Mother Vessel No       27895 non-null  object
 26  Shipping Bill No       38702 non-null  object
 27  Shipping Bill Date     38701 non-null  object
 28  BL No                  43806 non-null  object
 29  BL Date                43681 non-null  object
 30  FCR No                 43525 non-null  object
 31  FCR Date               43463 non-null  object
 32  Bank Ref No            43704 non-null  object
 33  Bank Submit Date       43704 non-null  object
 34  Expected Realize Date  6050 non-null   object
 35  Is FDBC                46518 non-null  object
 36  Bank Name              46517 non-null  object
 37  Shipping Mode          46518 non-null  object
 38  Invoice Status         46518 non-null  object
 39  Realize NO             43566 non-null  object
 40  Realize Date           43566 non-null  object
 41  Realize Value          43565 non-null  float64
 42  Is Realize             46518 non-null  object
dtypes: float64(7), int64(3), object(33)
memory usage: 15.6+ MB

In [8]:
df.describe()

,LC/SC Value,LC/SC Quantity,Invoice Qty,Carton Qty,Invoice Value,Discount,Commission,OnBoardDiff,Feeder Vessel No,Realize Value
count,4.651800e+04,4.651800e+04,46518.000000,45405.000000,46518.000000,46518.000000,46518.0,45831.000000,0.0,43565.000000
mean,6.301589e+06,1.727374e+06,995.861924,36.728356,4264.341601,45.096934,0.0,7.873644,NaN,4166.666261
std,4.289227e+06,1.429933e+06,3010.340657,201.629463,13876.124031,479.486241,0.0,83.854795,NaN,13495.418747
min,7.627500e+02,0.000000e+00,2.000000,0.000000,5.700000,0.000000,0.0,-725.000000,NaN,7.470000
25%,2.622975e+06,5.758130e+05,62.000000,1.000000,243.010000,0.000000,0.0,6.000000,NaN,240.900000
50%,4.542005e+06,1.244813e+06,181.000000,3.000000,673.910000,0.000000,0.0,8.000000,NaN,654.240000
75%,1.166402e+07,2.755553e+06,688.000000,11.000000,2568.367500,0.000000,0.0,10.000000,NaN,2485.020000
max,1.383651e+07,1.337135e+07,99066.000000,8740.000000,480570.440000,41584.520000,0.0,9903.000000,NaN,480570.220000

## 2. DataFrame Clean needed

In [9]:
import pandas as pd

# Define null-like values
null_values = [0, '0', '-', 'null', None]

all_null_string_columns = []

for column in df.columns:
    # Normalize values (convert to string + strip spaces + lower)
    col_series = df[column].astype(str).str.strip().str.lower()

    # Check if all values belong to null_values
    if col_series.isin([str(x).lower() for x in null_values]).all():
        all_null_string_columns.append(column)

print(f"Number of columns where all values are null-like: {len(all_null_string_columns)}")

if all_null_string_columns:
    print("\nColumns with only null-like values:")
    for col in all_null_string_columns:
        print(f"- {col}")
else:
    print("No columns found where all values are null-like.")

Number of columns where all values are null-like: 1

Columns with only null-like values:
- Commission

In [10]:
# ----------------------------
# Column Definitions
# ----------------------------
date_columns = [
    "BL Date", "Bank Submit Date", "EXP Date", "Ex Factory",
    "ExfactoryDate", "Expected Realize Date", "FCR Date",
    "Invoice Date", "On Board Date", "Payment Due Date",
    "Realize Date", "Shipping Bill Date"
]

numeric_int_columns = [
    "Commission", "Invoice Qty", "LC/SC Quantity"
]

numeric_float_columns = [
    "Discount", "Invoice Value", "LC/SC Value"
]

# ----------------------------
# Helper: Safe Date Parser
# ----------------------------
def safe_to_datetime(series):
    # Step 1: Clean text
    s = series.astype(str).str.strip()

    # Replace common junk values
    s = s.replace(
        ["", "nan", "None", "-", "--", "null", "NaT"],
        np.nan
    )

    # Step 2: Try multiple parsing strategies
    parsed = pd.to_datetime(s, errors='coerce', dayfirst=True)

    # Step 3: Try fallback (different format)
    fallback = pd.to_datetime(s, errors='coerce', format='%Y-%m-%d')

    # Step 4: Combine (priority: parsed → fallback → original)
    final = parsed.fillna(fallback)

    return final

# ----------------------------
# Helper: Safe Numeric Parser
# ----------------------------
def safe_to_numeric(series, is_int=False):
    s = series.astype(str).str.strip()

    # Remove commas, currency, spaces
    s = s.str.replace(',', '', regex=False)
    s = s.str.replace('৳', '', regex=False)
    s = s.str.replace('$', '', regex=False)

    # Replace junk
    s = s.replace(
        ["", "nan", "None", "-", "--", "null"],
        np.nan
    )

    num = pd.to_numeric(s, errors='coerce')

    if is_int:
        return num.round().astype("Int64")

    return num


# ----------------------------
# Convert DATE columns (SAFE)
# ----------------------------
for col in date_columns:
    if col in df.columns:
        original = df[col].copy()

        converted = safe_to_datetime(df[col])

        # Preserve original where conversion failed
        df[col] = converted.where(converted.notna(), original)

# ----------------------------
# Convert INTEGER columns (SAFE)
# ----------------------------
for col in numeric_int_columns:
    if col in df.columns:
        original = df[col].copy()

        converted = safe_to_numeric(df[col], is_int=True)

        df[col] = converted.where(converted.notna(), original)

# ----------------------------
# Convert FLOAT columns (SAFE)
# ----------------------------
for col in numeric_float_columns:
    if col in df.columns:
        original = df[col].copy()

        converted = safe_to_numeric(df[col], is_int=False)

        df[col] = converted.where(converted.notna(), original)

# ----------------------------
# Clean TEXT columns
# ----------------------------
text_columns = df.select_dtypes(include='object').columns

for col in text_columns:
    df[col] = df[col].astype(str).str.strip()

    df[col] = df[col].replace(
        ["nan", "None", "null", ""],
        np.nan
    )

# ----------------------------
# Optional: Debug problematic values
# ----------------------------
def find_bad_dates(df, col):
    mask = pd.to_datetime(df[col], errors='coerce').isna() & df[col].notna()
    return df.loc[mask, col].unique()

# Example debug:
# print(find_bad_dates(df, "Invoice Date"))

# ----------------------------
# Final Info
# ----------------------------
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 46518 entries, 198 to 15795
Data columns (total 43 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   LC Factory             46518 non-null  object
 1   LC/SC No               46518 non-null  object
 2   LC/SC Value            46518 non-null  float64
 3   LC/SC Quantity         46518 non-null  Int64
 4   LC/SC Payment Term     46509 non-null  object
 5   Invoice No             46518 non-null  object
 6   Invoice Date           46518 non-null  datetime64[ns]
 7   EXP No                 46461 non-null  object
 8   EXP Date               46518 non-null  datetime64[ns]
 9   Buyer                  46518 non-null  object
 10  PO No                  46507 non-null  object
 11  Merchandiser           46518 non-null  object
 12  Destination No         46515 non-null  object
 13  Invoice Qty            46518 non-null  Int64
 14  Carton Qty             45405 non-null  float64
 15  Invoice Value          46518 non-null  float64
 16  Discount               46518 non-null  float64
 17  Commission             46518 non-null  Int64
 18  ExfactoryDate          46407 non-null  datetime64[ns]
 19  Ex Factory No          46399 non-null  object
 20  Ex Factory             46399 non-null  object
 21  On Board Date          45848 non-null  datetime64[ns]
 22  Payment Due Date       45835 non-null  datetime64[ns]
 23  OnBoardDiff            45831 non-null  float64
 24  Feeder Vessel No       0 non-null      float64
 25  Mother Vessel No       27895 non-null  object
 26  Shipping Bill No       38701 non-null  object
 27  Shipping Bill Date     38701 non-null  datetime64[ns]
 28  BL No                  43806 non-null  object
 29  BL Date                43681 non-null  object
 30  FCR No                 43525 non-null  object
 31  FCR Date               43463 non-null  datetime64[ns]
 32  Bank Ref No            43704 non-null  object
 33  Bank Submit Date       43704 non-null  datetime64[ns]
 34  Expected Realize Date  6050 non-null   datetime64[ns]
 35  Is FDBC                46518 non-null  object
 36  Bank Name              46517 non-null  object
 37  Shipping Mode          46518 non-null  object
 38  Invoice Status         46518 non-null  object
 39  Realize NO             43566 non-null  object
 40  Realize Date           43566 non-null  object
 41  Realize Value          43565 non-null  float64
 42  Is Realize             46518 non-null  object
dtypes: Int64(3), datetime64[ns](9), float64(7), object(24)
memory usage: 15.7+ MB

In [11]:
# df_cols = df.columns

In [12]:
columns_to_drop = ['Payment Due Date','OnBoardDiff','Feeder Vessel No','Mother Vessel No', 'Expected Realize Date']
df = df.drop(columns=columns_to_drop)
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 46518 entries, 198 to 15795
Data columns (total 38 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   LC Factory          46518 non-null  object
 1   LC/SC No            46518 non-null  object
 2   LC/SC Value         46518 non-null  float64
 3   LC/SC Quantity      46518 non-null  Int64
 4   LC/SC Payment Term  46509 non-null  object
 5   Invoice No          46518 non-null  object
 6   Invoice Date        46518 non-null  datetime64[ns]
 7   EXP No              46461 non-null  object
 8   EXP Date            46518 non-null  datetime64[ns]
 9   Buyer               46518 non-null  object
 10  PO No               46507 non-null  object
 11  Merchandiser        46518 non-null  object
 12  Destination No      46515 non-null  object
 13  Invoice Qty         46518 non-null  Int64
 14  Carton Qty          45405 non-null  float64
 15  Invoice Value       46518 non-null  float64
 16  Discount            46518 non-null  float64
 17  Commission          46518 non-null  Int64
 18  ExfactoryDate       46407 non-null  datetime64[ns]
 19  Ex Factory No       46399 non-null  object
 20  Ex Factory          46399 non-null  object
 21  On Board Date       45848 non-null  datetime64[ns]
 22  Shipping Bill No    38701 non-null  object
 23  Shipping Bill Date  38701 non-null  datetime64[ns]
 24  BL No               43806 non-null  object
 25  BL Date             43681 non-null  object
 26  FCR No              43525 non-null  object
 27  FCR Date            43463 non-null  datetime64[ns]
 28  Bank Ref No         43704 non-null  object
 29  Bank Submit Date    43704 non-null  datetime64[ns]
 30  Is FDBC             46518 non-null  object
 31  Bank Name           46517 non-null  object
 32  Shipping Mode       46518 non-null  object
 33  Invoice Status      46518 non-null  object
 34  Realize NO          43566 non-null  object
 35  Realize Date        43566 non-null  object
 36  Realize Value       43565 non-null  float64
 37  Is Realize          46518 non-null  object
dtypes: Int64(3), datetime64[ns](7), float64(5), object(23)
memory usage: 14.0+ MB

In [13]:
df = df.rename(columns={

    'LC Factory': 'LC_Factory',
    'LC/SC No': 'LCSC_No',
    'LC/SC Value': 'LCSC_Value',
    'LC/SC Quantity': 'LCSC_Quantity',
    'LC/SC Payment Term': 'LCSC_Payment_Term',

    'Invoice No': 'Invoice_No',
    'Invoice Date': 'Invoice_Date',
    'Invoice Qty': 'Invoice_Qty',
    'Invoice Value': 'Invoice_Value',
    'Invoice Status': 'Invoice_Status',

    'EXP No': 'EXP_No',
    'EXP Date': 'EXP_Date',

    'PO No': 'PO_No',
    'Destination No': 'Destination',

    'Carton Qty': 'Carton_Qty',

    'ExfactoryDate': 'Ex_Factory_Date',
    'Ex Factory No': 'Ex_Factory_No',
    'Ex Factory': 'Ex_Factory',

    'On Board Date': 'On_Board_Date',

    'Shipping Bill No': 'Shipping_Bill_No',
    'Shipping Bill Date': 'Shipping_Bill_Date',
    'Shipping Mode': 'Shipping_Mode',

    'BL No': 'BL_No',
    'BL Date': 'BL_Date',

    'FCR No': 'FCR_No',
    'FCR Date': 'FCR_Date',

    'Bank Ref No': 'FDBC_No',
    'Bank Submit Date': 'Bank_Submit_Date',
    'Bank Name': 'Bank_Name',

    'Is FDBC': 'Is_FDBC',

    'Realize NO': 'Realize_No',
    'Realize Date': 'Realize_Date',
    'Realize Value': 'Realize_Value',

    'Is Realize': 'Is_Realize',

    'Shipping Mode': 'Shipping_Mode'

})

df.columns

Index(['LC_Factory', 'LCSC_No', 'LCSC_Value', 'LCSC_Quantity',
       'LCSC_Payment_Term', 'Invoice_No', 'Invoice_Date', 'EXP_No', 'EXP_Date',
       'Buyer', 'PO_No', 'Merchandiser', 'Destination', 'Invoice_Qty',
       'Carton_Qty', 'Invoice_Value', 'Discount', 'Commission',
       'Ex_Factory_Date', 'Ex_Factory_No', 'Ex_Factory', 'On_Board_Date',
       'Shipping_Bill_No', 'Shipping_Bill_Date', 'BL_No', 'BL_Date', 'FCR_No',
       'FCR_Date', 'FDBC_No', 'Bank_Submit_Date', 'Is_FDBC', 'Bank_Name',
       'Shipping_Mode', 'Invoice_Status', 'Realize_No', 'Realize_Date',
       'Realize_Value', 'Is_Realize'],
      dtype='object')

In [14]:
df["Category"] = np.where(
    df["LC_Factory"].isin(["MFSL", "MGKFL"]),
    "Sweater",
    "Woven"
)

In [15]:
df.columns

Index(['LC_Factory', 'LCSC_No', 'LCSC_Value', 'LCSC_Quantity',
       'LCSC_Payment_Term', 'Invoice_No', 'Invoice_Date', 'EXP_No', 'EXP_Date',
       'Buyer', 'PO_No', 'Merchandiser', 'Destination', 'Invoice_Qty',
       'Carton_Qty', 'Invoice_Value', 'Discount', 'Commission',
       'Ex_Factory_Date', 'Ex_Factory_No', 'Ex_Factory', 'On_Board_Date',
       'Shipping_Bill_No', 'Shipping_Bill_Date', 'BL_No', 'BL_Date', 'FCR_No',
       'FCR_Date', 'FDBC_No', 'Bank_Submit_Date', 'Is_FDBC', 'Bank_Name',
       'Shipping_Mode', 'Invoice_Status', 'Realize_No', 'Realize_Date',
       'Realize_Value', 'Is_Realize', 'Category'],
      dtype='object')

In [16]:
# ----------------------------
# 1. Add Serial Column
# ----------------------------
df.insert(0, "SL#", range(1, len(df) + 1))

# ----------------------------
# 2. Define final column order
# ----------------------------
desired_order = [
    "SL#",
    "Category",

    "LC_Factory",
    "LCSC_No",
    "LCSC_Value",
    "LCSC_Quantity",
    "LCSC_Payment_Term",

    "Invoice_No",
    "Invoice_Date",
    "Invoice_Value",
    "Invoice_Qty",

    "EXP_No",
    "EXP_Date",

    "Buyer",
    "Merchandiser",
    "Destination",

    "Carton_Qty",
    "Discount",
    "Commission",

    "Ex_Factory_Date",
    "Ex_Factory_No",
    "Ex_Factory",
    "On_Board_Date",

    "Shipping_Bill_No",
    "Shipping_Bill_Date",
    "Shipping_Mode",

    "BL_No",
    "BL_Date",

    "FCR_No",
    "FCR_Date",

    "Bank_Name",
    "FDBC_No",
    "Bank_Submit_Date",
    "Is_FDBC",

    "Invoice_Status",

    "Realize_No",
    "Realize_Date",
    "Realize_Value",
    "Is_Realize",

    "PO_No"
]

# ----------------------------
# 3. Reorder safely (avoid missing column error)
# ----------------------------
df = df[[col for col in desired_order if col in df.columns]]

In [17]:
#######Save Excel File########
df.to_excel("OUTPUT/EIS.xlsx", index=False)

## 3. Pending Data Extraction

In [18]:
Buyer_Payment = pd.read_csv("Data\Buyer_Payment_Chart.csv")

In [19]:
Buyer_Payment.sample(5)

,Sl. No.,Buyer,Export Responsible,Ex-Factory,Days,Onboard,Days.1,B/L Collection,Days.2,Bank Doc Submission,Days.3,Payment Term,Payment Date,Remarks,Payment After Ex-Factory
64,65,LOJAS RENNER,Sajjad,01-01-2026,7.0,08-01-2026,10.0,18-01-2026,NaN,NaN,NaN,10,28-01-2026,NaN,27
80,81,Promoset SA,NaN,01-01-2026,7.0,08-01-2026,3.0,11-01-2026,NaN,NaN,NaN,10,21-01-2026,not update,20
89,90,STREET ONE GMBH,NaN,01-01-2026,7.0,08-01-2026,3.0,11-01-2026,NaN,NaN,NaN,10,21-01-2026,NaN,20
34,35,CECIL GMBH,NaN,01-01-2026,7.0,08-01-2026,3.0,11-01-2026,NaN,NaN,NaN,25,05-02-2026,not update,35
88,89,Street One,NaN,01-01-2026,7.0,08-01-2026,3.0,11-01-2026,NaN,NaN,NaN,10,21-01-2026,NaN,20

In [20]:
Buyer_Payment.shape

(124, 15)

### 3.1 Realize Pending Report Generate

In [21]:
df.Invoice_Status.unique()

array(['Incentive Pending', 'On Board Pending', 'Bank Submit Pending',
       'ExFactory Pending', 'Realize Pending', 'For Booking'],
      dtype=object)

In [22]:
# Merge based on Buyer name
df = df.merge(
    Buyer_Payment[['Buyer', 'Payment After Ex-Factory']],
    on='Buyer',
    how='left'   # Keep all EIS rows
)
# Rename column
df.rename(columns={
    'Payment After Ex-Factory': 'PaymentAfterExFactory'
}, inplace=True)

In [23]:
cols = df.columns.tolist()

if 'PaymentAfterExFactory' in cols and 'Invoice_No' in cols:
    cols.insert(cols.index('Invoice_No'), cols.pop(cols.index('PaymentAfterExFactory')))
    df = df[cols]
else:
    raise KeyError("Missing required columns for reorder")

In [24]:
Realize_Report = df[df['Invoice_Status'] == "Realize Pending"]

In [25]:
Realize_Report.columns

Index(['SL#', 'Category', 'LC_Factory', 'LCSC_No', 'LCSC_Value',
       'LCSC_Quantity', 'LCSC_Payment_Term', 'PaymentAfterExFactory',
       'Invoice_No', 'Invoice_Date', 'Invoice_Value', 'Invoice_Qty', 'EXP_No',
       'EXP_Date', 'Buyer', 'Merchandiser', 'Destination', 'Carton_Qty',
       'Discount', 'Commission', 'Ex_Factory_Date', 'Ex_Factory_No',
       'Ex_Factory', 'On_Board_Date', 'Shipping_Bill_No', 'Shipping_Bill_Date',
       'Shipping_Mode', 'BL_No', 'BL_Date', 'FCR_No', 'FCR_Date', 'Bank_Name',
       'FDBC_No', 'Bank_Submit_Date', 'Is_FDBC', 'Invoice_Status',
       'Realize_No', 'Realize_Date', 'Realize_Value', 'Is_Realize', 'PO_No'],
      dtype='object')

In [26]:
# -------------------------------
# INPUT DATAFRAME (change name if needed)
# -------------------------------
Realize_Report = df.copy()

# -------------------------------
# NORMALIZE COLUMNS & DROP DUPLICATES
# -------------------------------
Realize_Report.columns = Realize_Report.columns.str.strip()
Realize_Report = Realize_Report.loc[:, ~Realize_Report.columns.duplicated()]

# -------------------------------
# SAFE DATE & NUMERIC CONVERSIONS
# -------------------------------
date_cols = [
    'Invoice_Date', 'EXP_Date', 'Ex_Factory_Date',
    'On_Board_Date', 'Bank_Submit_Date', 'Realize_Date'
]
for c in date_cols:
    if c in Realize_Report.columns:
        Realize_Report[c] = pd.to_datetime(Realize_Report[c], errors='coerce')

numeric_cols = ['Invoice_Value', 'PaymentAfterExFactory']
for c in numeric_cols:
    if c in Realize_Report.columns:
        Realize_Report[c] = pd.to_numeric(Realize_Report[c], errors='coerce')

# -------------------------------
# NORMALIZE/VALIDATE BANK REF (FDBC_No)
# -------------------------------
if 'FDBC_No' in Realize_Report.columns:
    Realize_Report['FDBC_No'] = Realize_Report['FDBC_No'].astype(str).str.strip()
    Realize_Report.loc[Realize_Report['FDBC_No'].str.lower() == 'nan', 'FDBC_No'] = np.nan

# drop rows without a Bank Ref No
Realize_Report = Realize_Report.dropna(subset=['FDBC_No']).copy()

# -------------------------------
# PREP: invoice column
# -------------------------------
invoice_col = 'Invoice_No'
if invoice_col not in Realize_Report.columns and 'Invoice' in Realize_Report.columns:
    invoice_col = 'Invoice'

# -------------------------------
# ONBOARD DATE RANGE (group-level)
# -------------------------------
onboard_range = (
    Realize_Report.groupby('FDBC_No', as_index=False)['On_Board_Date']
      .agg(min_onboard='min', max_onboard='max')
)

# -------------------------------
# INVOICE LIST (unique, sorted)
# -------------------------------
invoice_list = (
    Realize_Report.dropna(subset=[invoice_col])
      .assign(__inv_str=lambda d: d[invoice_col].astype(str).str.strip())
      .sort_values('__inv_str')
      .drop_duplicates(['FDBC_No', '__inv_str'])
      .groupby('FDBC_No', as_index=False)['__inv_str']
      .agg(INVOICES=lambda s: ",".join(s))
)

# -------------------------------
# AGGREGATE / GROUP BY FDBC_No
# -------------------------------
summary = (
    Realize_Report.groupby('FDBC_No', as_index=False)
      .agg(
          Status=('Invoice_Status', 'first'),
          Category=('Category', 'first'),
          Buyer=('Buyer', 'first'),
          Company=('LC_Factory', 'first'),           # Factory -> Company
          Bank=('Bank_Name', 'first'),
          PaymentTermXFactory=('PaymentAfterExFactory', 'first'),
          ExFactoryDate=('Ex_Factory_Date', 'max'),    # last date
          BankSubmitDate=('Bank_Submit_Date', 'max'),  # last date
          InvoiceDate=('Invoice_Date', 'max'),        # last invoice date
          Total_Invoices=(invoice_col, lambda s: s.dropna().count()),
          Total_Invoice_Value=('Invoice_Value', 'sum')
      )
)

# -------------------------------
# MERGE onboard_range & invoice_list
# -------------------------------
summary = summary.merge(onboard_range, on='FDBC_No', how='left')
summary = summary.merge(invoice_list, on='FDBC_No', how='left')

# Ensure INVOICES column exists
if 'INVOICES' not in summary.columns:
    summary['INVOICES'] = ""

# -------------------------------
# IsBankSubmit? (YES/NO)
# -------------------------------
summary['IsBankSubmit?'] = np.where(summary['BankSubmitDate'].notna(), 'YES', 'NO')

# -------------------------------
# OnBoardDate(Range) formatting
# -------------------------------
def format_onboard(rmin, rmax):
    if pd.isna(rmin) or pd.isna(rmax):
        return ""
    return f"{rmin.strftime('%d-%b-%Y')} to {rmax.strftime('%d-%b-%Y')}"

summary['OnBoardDate(Range)'] = summary.apply(
    lambda r: format_onboard(r['min_onboard'], r['max_onboard']), axis=1
)

summary.drop(columns=['min_onboard', 'max_onboard'], inplace=True)

# -------------------------------
# IsFDBCRealizable? (group-level)
# -------------------------------
today = pd.Timestamp.today().normalize()
summary['PaymentTermXFactory'] = pd.to_numeric(summary['PaymentTermXFactory'], errors='coerce')

summary['Due_Date'] = pd.NaT
mask = summary['PaymentTermXFactory'].notna() & summary['ExFactoryDate'].notna()
if mask.any():
    summary.loc[mask, 'Due_Date'] = (
        summary.loc[mask, 'ExFactoryDate'] +
        pd.to_timedelta(summary.loc[mask, 'PaymentTermXFactory'].astype(float), unit='D')
    )

def realizable_status(row):
    if pd.isna(row['PaymentTermXFactory']) or pd.isna(row['Due_Date']):
        return ""
    return 'NeedRealize' if today > row['Due_Date'] else 'NotYetRealize'

summary['IsFDBCRealizable?'] = summary.apply(realizable_status, axis=1)
summary.drop(columns=['Due_Date'], inplace=True)

# -------------------------------
# FINAL CLEANUP & ORDERING
# -------------------------------
summary.insert(0, 'SL#', range(1, len(summary) + 1))

final_cols = [
    'SL#',
    'FDBC_No',                # will rename to 'Bank Ref No'
    'Status',
    'Category',
    'Buyer',
    'Company',
    'IsBankSubmit?',
    'ExFactoryDate',
    'Bank',
    'BankSubmitDate',
    'PaymentTermXFactory',
    'OnBoardDate(Range)',
    'Total_Invoices',
    'Total_Invoice_Value',
    'InvoiceDate',            # last Invoice date added
    'IsFDBCRealizable?',
    'INVOICES'
]

for c in final_cols:
    if c not in summary.columns:
        summary[c] = "" if summary.shape[0] > 0 else pd.Series(dtype=object)

summary = summary[final_cols]

summary['Total_Invoice_Value'] = pd.to_numeric(summary['Total_Invoice_Value'], errors='coerce').fillna(0)

# -------------------------------
# FINAL OUTPUT
# -------------------------------
RealizePending = summary.copy()
print("Realize Pending Table Created Successfully")

Realize Pending Table Created Successfully

In [27]:
RealizePending.sample(5)

,SL#,FDBC_No,Status,Category,Buyer,Company,IsBankSubmit?,ExFactoryDate,Bank,BankSubmitDate,PaymentTermXFactory,OnBoardDate(Range),Total_Invoices,Total_Invoice_Value,InvoiceDate,IsFDBCRealizable?,INVOICES
866,867,4273/24,Incentive Pending,Sweater,Matalan,MGKFL,YES,2024-10-17,DBBL,2024-11-27,NaN,17-Sep-2024 to 18-Nov-2024,3,20788.44,2024-10-17,,"2412179,2415172,2415308"
627,628,2875/2025,Incentive Pending,Sweater,WEATHERPROOF VINTAGE,MGKFL,YES,2025-07-09,DBBL,2025-08-04,44.0,13-Jul-2025 to 13-Jul-2025,1,25707.60,2025-07-09,NeedRealize,2508780
546,547,2512/25,Incentive Pending,Woven,Springfield,MGL,YES,2025-05-26,EXIM,2025-07-07,31.0,04-Jun-2025 to 04-Jun-2025,1,20948.48,2025-05-27,NeedRealize,2507354
1370,1371,FDBC-260310,Incentive Pending,Woven,Springfield,MGL,YES,2026-02-24,OBL,2026-03-31,31.0,03-Feb-2026 to 28-Feb-2026,8,842850.19,2026-02-24,NeedRealize,"2601442,2601443,2601798,2601801,2602223,260234..."
307,308,1417/25,Incentive Pending,Woven,EL CORTE INGLES,MGL,YES,2025-02-25,EXIM,2025-04-17,120.0,25-Feb-2025 to 25-Feb-2025,1,2970.00,2025-02-20,NeedRealize,2503040

In [28]:
Nowshin = RealizePending[RealizePending['Category'] == "Sweater"]
Tonni = RealizePending[RealizePending['Company'] == "MGL"]
Arif = RealizePending[RealizePending['Company'] == "MGSL"]
Manzarul = RealizePending[RealizePending['Company'] == "MGNSL"]

In [29]:
#######Save Excel Files########
RealizePending.to_excel("OUTPUT/RealizeReports/RealizePending.xlsx", index=False)

Nowshin.to_excel("OUTPUT/RealizeReports/Nowshin.xlsx", index=False)
Tonni.to_excel("OUTPUT/RealizeReports/Tonni.xlsx", index=False)
Arif.to_excel("OUTPUT/RealizeReports/Arif.xlsx", index=False)
Manzarul.to_excel("OUTPUT/RealizeReports/Manzarul.xlsx", index=False)

In [30]:
df['Invoice_Status'].value_counts()

Invoice_Status
Incentive Pending      43454
Bank Submit Pending     2254
On Board Pending         568
Realize Pending          128
ExFactory Pending         82
For Booking               37
Name: count, dtype: int64

### 3.2 On Board Pending Generate

In [31]:
OnBoardPending = df[df['Invoice_Status'] == "On Board Pending"]

In [32]:
OnBoardPending.sample(5)

,SL#,Category,LC_Factory,LCSC_No,LCSC_Value,LCSC_Quantity,LCSC_Payment_Term,PaymentAfterExFactory,Invoice_No,Invoice_Date,...,Bank_Name,FDBC_No,Bank_Submit_Date,Is_FDBC,Invoice_Status,Realize_No,Realize_Date,Realize_Value,Is_Realize,PO_No
32650,32648,Woven,MGSL,MGSL/H&M-Mens DBL-S.04,6738847.77,1772529,EOM+63,6.0,2604329,2026-04-16,...,DBBL,NaN,NaT,No,On Board Pending,NaN,NaN,NaN,No,586575-5777
45757,45754,Woven,MGSL,DC HK1178515,226447.68,35088,At Sight,28.0,2602425,2026-02-19,...,DBBL,FDBC-0896/26,2026-02-25,Yes,On Board Pending,DR-03-26-025,2026-03-15 00:00:00,12063.96,Yes,"5100326997, 5100326996"
13853,13852,Woven,MGL,ECI-AW26,3004841.40,798820,At Sight,120.0,2603213,2026-03-10,...,OBL,FDBC-260357,2026-04-08,Yes,On Board Pending,DR-04-26-037,2026-04-09 00:00:00,4039.40,Yes,0167290414601
4465,4466,Woven,MGSL,MGSL/H&M-MENS -S.07,2948973.12,763766,EOM 63,6.0,MGSL/23/3020,2023-04-20,...,ABL,NaN,NaT,No,On Board Pending,NaN,NaN,NaN,No,556397-8617
21435,21434,Woven,MGSL,MGSL/ H&M Kids S3 ABL,1004412.30,299653,EOM+63,6.0,2604637,2026-04-26,...,ABL,NaN,NaT,No,On Board Pending,NaN,NaN,NaN,No,605943-7657

In [33]:
OnBoardPending.columns

Index(['SL#', 'Category', 'LC_Factory', 'LCSC_No', 'LCSC_Value',
       'LCSC_Quantity', 'LCSC_Payment_Term', 'PaymentAfterExFactory',
       'Invoice_No', 'Invoice_Date', 'Invoice_Value', 'Invoice_Qty', 'EXP_No',
       'EXP_Date', 'Buyer', 'Merchandiser', 'Destination', 'Carton_Qty',
       'Discount', 'Commission', 'Ex_Factory_Date', 'Ex_Factory_No',
       'Ex_Factory', 'On_Board_Date', 'Shipping_Bill_No', 'Shipping_Bill_Date',
       'Shipping_Mode', 'BL_No', 'BL_Date', 'FCR_No', 'FCR_Date', 'Bank_Name',
       'FDBC_No', 'Bank_Submit_Date', 'Is_FDBC', 'Invoice_Status',
       'Realize_No', 'Realize_Date', 'Realize_Value', 'Is_Realize', 'PO_No'],
      dtype='object')

In [34]:
columns_to_drop = ['LCSC_No', 'LCSC_Value','LCSC_Quantity', 'LCSC_Payment_Term', 'PaymentAfterExFactory',
                   'Merchandiser','BL_No', 'BL_Date', 'FCR_No', 'FCR_Date','Carton_Qty','Discount', 'Commission','Shipping_Bill_No', 
                   'Shipping_Bill_Date','Realize_No', 'Realize_Date', 'Realize_Value','PO_No']

OnBoardPending = OnBoardPending.drop(columns=columns_to_drop)
OnBoardPending.sample(3)

,SL#,Category,LC_Factory,Invoice_No,Invoice_Date,Invoice_Value,Invoice_Qty,EXP_No,EXP_Date,Buyer,...,Ex_Factory_No,Ex_Factory,On_Board_Date,Shipping_Mode,Bank_Name,FDBC_No,Bank_Submit_Date,Is_FDBC,Invoice_Status,Is_Realize
5769,5770,Woven,MGSL,2604592,2026-04-26,37200.78,7983,00000042-002592-2026,2026-04-27,H&M,...,MGSL-EF260679,MGSL,NaT,Sea,ABL,NaN,NaT,No,On Board Pending,No
43945,43942,Woven,MGSL,2604408,2026-04-19,386.40,184,00001689-010094-2026,2026-04-19,H&M,...,MGSL-EF260680,MGSL,NaT,Sea,DBBL,NaN,NaT,No,On Board Pending,No
18259,18258,Woven,MGSL,2604699,2026-04-26,1117.92,408,00001689-010680-2026,2026-04-26,H&M,...,MGSL-EF260674,MGNSL,NaT,Sea,DBBL,NaN,NaT,No,On Board Pending,No

### 3.3 Ex Factory Pending Generate

In [35]:
ExFactoryPending = df[df['Invoice_Status'] == "ExFactory Pending"]

In [36]:
ExFactoryPending.columns

Index(['SL#', 'Category', 'LC_Factory', 'LCSC_No', 'LCSC_Value',
       'LCSC_Quantity', 'LCSC_Payment_Term', 'PaymentAfterExFactory',
       'Invoice_No', 'Invoice_Date', 'Invoice_Value', 'Invoice_Qty', 'EXP_No',
       'EXP_Date', 'Buyer', 'Merchandiser', 'Destination', 'Carton_Qty',
       'Discount', 'Commission', 'Ex_Factory_Date', 'Ex_Factory_No',
       'Ex_Factory', 'On_Board_Date', 'Shipping_Bill_No', 'Shipping_Bill_Date',
       'Shipping_Mode', 'BL_No', 'BL_Date', 'FCR_No', 'FCR_Date', 'Bank_Name',
       'FDBC_No', 'Bank_Submit_Date', 'Is_FDBC', 'Invoice_Status',
       'Realize_No', 'Realize_Date', 'Realize_Value', 'Is_Realize', 'PO_No'],
      dtype='object')

In [37]:
columns_to_drop = ['LCSC_No', 'LCSC_Value','LCSC_Quantity', 'LCSC_Payment_Term', 'PaymentAfterExFactory',
                   'Merchandiser','BL_No', 'BL_Date', 'FCR_No', 'FCR_Date','Carton_Qty','Discount', 'Commission','Shipping_Bill_No', 
                   'Shipping_Bill_Date','Realize_No', 'Realize_Date', 'Realize_Value','PO_No']

ExFactoryPending = ExFactoryPending.drop(columns=columns_to_drop)
ExFactoryPending.sample(3)

,SL#,Category,LC_Factory,Invoice_No,Invoice_Date,Invoice_Value,Invoice_Qty,EXP_No,EXP_Date,Buyer,...,Ex_Factory_No,Ex_Factory,On_Board_Date,Shipping_Mode,Bank_Name,FDBC_No,Bank_Submit_Date,Is_FDBC,Invoice_Status,Is_Realize
12282,12281,Woven,MGNSL,2604404,2026-04-16,15000.00,3000,NaN,2026-04-16,LOJAS RENNER,...,NaN,NaN,NaT,Sea,ABL,NaN,NaT,No,ExFactory Pending,No
21123,21122,Woven,MGSL,2603943,2026-04-05,64.62,18,00001689-008834-2026,2026-04-05,H&M,...,NaN,NaN,NaT,Sea,DBBL,NaN,NaT,No,ExFactory Pending,No
19473,19472,Woven,MGSL,MGSL/23/3391,2023-05-10,4063.50,1290,006087,2023-05-10,H&M,...,NaN,NaN,2023-05-17,Sea,ABL,FDBC-516/2023,2023-06-08,Yes,ExFactory Pending,Yes

### 3.4 Bank Submit Pending Generate

In [38]:
BankSubmitPending = df[df['Invoice_Status'] == "Bank Submit Pending"]

In [39]:
BankSubmitPending.columns

Index(['SL#', 'Category', 'LC_Factory', 'LCSC_No', 'LCSC_Value',
       'LCSC_Quantity', 'LCSC_Payment_Term', 'PaymentAfterExFactory',
       'Invoice_No', 'Invoice_Date', 'Invoice_Value', 'Invoice_Qty', 'EXP_No',
       'EXP_Date', 'Buyer', 'Merchandiser', 'Destination', 'Carton_Qty',
       'Discount', 'Commission', 'Ex_Factory_Date', 'Ex_Factory_No',
       'Ex_Factory', 'On_Board_Date', 'Shipping_Bill_No', 'Shipping_Bill_Date',
       'Shipping_Mode', 'BL_No', 'BL_Date', 'FCR_No', 'FCR_Date', 'Bank_Name',
       'FDBC_No', 'Bank_Submit_Date', 'Is_FDBC', 'Invoice_Status',
       'Realize_No', 'Realize_Date', 'Realize_Value', 'Is_Realize', 'PO_No'],
      dtype='object')

In [40]:
columns_to_drop = ['LCSC_No', 'LCSC_Value','LCSC_Quantity', 'LCSC_Payment_Term', 'PaymentAfterExFactory',
                   'Merchandiser','BL_No', 'BL_Date', 'FCR_No', 'FCR_Date','Carton_Qty','Discount', 'Commission',
                   'Realize_No', 'Realize_Date', 'Realize_Value','PO_No']

BankSubmitPending = BankSubmitPending.drop(columns=columns_to_drop)
BankSubmitPending.sample(3)

,SL#,Category,LC_Factory,Invoice_No,Invoice_Date,Invoice_Value,Invoice_Qty,EXP_No,EXP_Date,Buyer,...,On_Board_Date,Shipping_Bill_No,Shipping_Bill_Date,Shipping_Mode,Bank_Name,FDBC_No,Bank_Submit_Date,Is_FDBC,Invoice_Status,Is_Realize
19167,19166,Woven,MGSL,2314167,2023-10-05,3341.44,736,042/015161/23,2023-10-05,H&M,...,2023-10-11,C-1564203,2023-10-07,Sea,ABL,NaN,NaT,No,Bank Submit Pending,No
38326,38324,Woven,MGSL,2603340,2026-03-12,634.88,128,00001689-007476-2026,2026-03-12,H&M,...,2026-03-19,NaN,NaT,Sea,DBBL,NaN,NaT,No,Bank Submit Pending,No
15226,15225,Woven,MGSL,2603256,2026-03-11,9663.78,3287,00001689-007317-2026,2026-03-11,H&M,...,2026-03-23,NaN,NaT,Air,DBBL,NaN,NaT,No,Bank Submit Pending,No

In [41]:
#######Save Excel Files########
OnBoardPending.to_excel("OUTPUT/OnBoardPending.xlsx", index=False)
ExFactoryPending.to_excel("OUTPUT/ExFactoryPending.xlsx", index=False)
BankSubmitPending.to_excel("OUTPUT/BankSubmitPending.xlsx", index=False)