In [1]:
#### Load libraries #####
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import os
import warnings
warnings.filterwarnings('ignore')

In [2]:
#### Load Dataset
EIS_WO = pd.read_excel("Data/EIS_WO.xlsx")
EIS_SW = pd.read_excel("Data/EIS_SW.xlsx")

In [3]:
payment_method = pd.read_csv("Data/Buyer_Payment_Chart.csv")

In [4]:
print("Export Invoice Summary for Woven")
display(EIS_WO.head(5))
print("Export Invoice Summary for Sweater")
display(EIS_SW.head(5))

Export Invoice Summary for Woven

,LC Factory,LC/SC No,LC/SC Value,LC/SC Quantity,LC/SC Payment Term,Invoice No,Invoice Date,EXP No,EXP Date,Buyer,...,Bank Submit Date,Expected Realize Date,Is FDBC,Bank Name,Shipping Mode,Invoice Status,Realize NO,Realize Date,Realize Value,Is Realize
0,MGSL,MGSL/Polly Slim Fit Shirt S. 8,96325.68,20677,EOM 63,2310013,09-May-2023,042/006812/23,27-May-2023,H&M,...,08-Jun-2023,NaN,Yes,ABL,Sea,Incentive Pending,DR-06-23-002,08-Jun-2023,1706.60,Yes
1,MGSL,MGSL/Polly Slim Fit Shirt S. 8,96325.68,20677,EOM 63,2310015,09-May-2023,042/006815/23,27-May-2023,H&M,...,08-Jun-2023,NaN,Yes,ABL,Sea,Incentive Pending,DR-06-23-002,08-Jun-2023,87.40,Yes
2,MGL,MG-Pepe Jeans Denim-24,1536453.18,118136,90 Days,2310017,10-May-2023,1949/009162/23,12-Apr-2023,PEPE JEANS SL,...,15-May-2023,NaN,Yes,EXIM,Sea,ExFactory Pending,DR-09-23-005,04-Sep-2023,6268.22,Yes
3,MGSL,MGSL/Robin Oxford Shirt S. 8,2622975.35,501569,60 Days,2310019,11-May-2023,042/006782/23,25-May-2023,H&M,...,NaN,NaN,No,ABL,Sea,ExFactory Pending,NaN,NaN,NaN,No
4,MGSL,MGSL/Robin Oxford Shirt S. 8,2622975.35,501569,60 Days,2310020,05-May-2023,042/006783/23,25-May-2023,H&M,...,08-Aug-2023,NaN,Yes,ABL,Sea,Incentive Pending,DR-08-23-015,08-Aug-2023,2823.10,Yes

Export Invoice Summary for Sweater

,LC Factory,LC/SC No,LC/SC Value,LC/SC Quantity,LC/SC Payment Term,Invoice No,Invoice Date,EXP No,EXP Date,Buyer,...,Bank Submit Date,Expected Realize Date,Is FDBC,Bank Name,Shipping Mode,Invoice Status,Realize NO,Realize Date,Realize Value,Is Realize
0,MGKFL,LI23J00912,209075.00,25200,75 Days,2310036,18-Apr-2023,1689/006989/23,18-Apr-2023,DK Company,...,11-May-2023,NaN,Yes,DBBL,Sea,Realize Pending,NaN,NaN,NaN,No
1,MGKFL,MGKL/WP/002/2023,150120.00,21600,14 Days,2310067,23-May-2023,1689/009568/23,08-Jun-2023,WEATHERPROOF VINTAGE,...,24-Jul-2023,NaN,Yes,DBBL,Sea,Realize Pending,NaN,NaN,NaN,No
2,MFSL,3522-RIR2391792,120742.81,21775,At Sight,2310069,20-Apr-2023,0042/006384/23,16-May-2023,Hellenic Trading AB,...,28-May-2023,NaN,Yes,ABL,Sea,ExFactory Pending,NaN,NaN,NaN,No
3,MFSL,AWWA/VCL/MFSL/01/2023,83310.15,16575,At Sight,2310389,21-May-2023,2155/003022/23,30-May-2023,Assurer Worldwide Apparel LLC.,...,11-Jun-2023,NaN,Yes,PRM,Sea,Incentive Pending,DR-08-23-012,02-Aug-2023,39928.15,Yes
4,MGKFL,MGKL/WP/002/2023,150120.00,21600,14 Days,2310494,21-Jun-2023,1689/010576/23,21-Jun-2023,WEATHERPROOF VINTAGE,...,24-Jul-2023,NaN,Yes,DBBL,Sea,Realize Pending,NaN,NaN,NaN,No

In [5]:
try:
    cols_wo = set(EIS_WO.columns)
    cols_sw = set(EIS_SW.columns)

    if cols_wo == cols_sw:
        print("✅ All column names are matched perfectly.")
    else:
        print("❌ Column mismatch detected.\n")

        print("Columns in EIS_WO but NOT in EIS_SW:")
        print(cols_wo - cols_sw)

        print("\nColumns in EIS_SW but NOT in EIS_WO:")
        print(cols_sw - cols_wo)

except NameError as e:
    print("⚠ Dataset variable not defined:", e)

except AttributeError as e:
    print("⚠ One of the objects is not a valid DataFrame:", e)

except Exception as e:
    print("⚠ Unexpected error occurred:", e)

✅ All column names are matched perfectly.

In [6]:
### Combined Datasets to make one EIS Dataset ,e.g : EIS = EIS_WO + EIS_SW

EIS_Combined = pd.concat([EIS_WO,EIS_SW], ignore_index = True)
EIS_Combined.tail(10)

,LC Factory,LC/SC No,LC/SC Value,LC/SC Quantity,LC/SC Payment Term,Invoice No,Invoice Date,EXP No,EXP Date,Buyer,...,Bank Submit Date,Expected Realize Date,Is FDBC,Bank Name,Shipping Mode,Invoice Status,Realize NO,Realize Date,Realize Value,Is Realize
44163,MGKFL,MGKFL/MKNMMA/02/2026,73955.70,11826,90 Days,2600457,08-Jan-2026,00001689-002646-2026,25-Jan-2026,Best Seller,...,NaN,NaN,No,DBBL,Sea/Air,Bank Submit Pending,NaN,NaN,NaN,No
44164,MGKFL,MGKFL/MKNLOJ/01/2026,137069.08,25497,90 Days,2600458,08-Jan-2026,00001689-002264-2026,21-Jan-2026,Best Seller,...,NaN,NaN,No,DBBL,Sea,Bank Submit Pending,NaN,NaN,NaN,No
44165,MFSL,MFSL-CHOUSE-25-262,7752.00,1275,15 Days,2600460,08-Jan-2026,00002155-000591-2026,22-Jan-2026,Hellenic Sourcing Hong Kong Ltd.,...,10-Feb-2026,10-Feb-2026,Yes,PRM,Sea,On Board Pending,NaN,NaN,NaN,No
44166,MFSL,LI25J03345,19875.00,3000,L/C - 75 days,2601184,19-Jan-2026,00002155-000953-2026,01-Feb-2026,DK COMPANY CPH A/S,...,NaN,NaN,No,PRM,Sea,Bank Submit Pending,NaN,NaN,NaN,No
44167,MFSL,LI25J03345,19875.00,3000,L/C - 75 days,2601185,19-Jan-2026,00002155-000544-2026,20-Jan-2026,DK COMPANY CPH A/S,...,NaN,NaN,No,PRM,Air,Bank Submit Pending,NaN,NaN,NaN,No
44168,MFSL,LI25J03308,63861.65,10734,L/C - 75 days,2601197,21-Jan-2026,00002155-000576-2026,21-Jan-2026,DK COMPANY CPH A/S,...,16-Feb-2026,09-May-2026,Yes,PRM,Sea,Realize Pending,NaN,NaN,NaN,No
44169,MFSL,LI25J03308,63861.65,10734,L/C - 75 days,2601198,21-Jan-2026,00002155-000577-2026,21-Jan-2026,DK Company,...,16-Feb-2026,09-May-2026,Yes,PRM,Sea,Realize Pending,NaN,NaN,NaN,No
44170,MFSL,LI25J03308,63861.65,10734,L/C - 75 days,2601419,26-Jan-2026,00002155-000770-2026,27-Jan-2026,DK Company,...,NaN,NaN,No,PRM,Sea,Bank Submit Pending,NaN,NaN,NaN,No
44171,MFSL,LI25J03308,63861.65,10734,L/C - 75 days,2601420,26-Jan-2026,00002155-000771-2026,27-Jan-2026,DK Company,...,NaN,NaN,No,PRM,Sea,Bank Submit Pending,NaN,NaN,NaN,No
44172,MFSL,LI25J03345,19875.00,3000,L/C - 75 days,2601790,02-Feb-2026,00002155-000985-2026,02-Feb-2026,DK Company,...,NaN,NaN,No,PRM,Sea,Bank Submit Pending,NaN,NaN,NaN,No

In [7]:
#### Shuffle the dataset for better Analysis

try:
    EIS_Shuffled = EIS_Combined.sample(frac=1, random_state=42).reset_index(drop=True)
    print("✅ Data shuffled successfully.")
except Exception as e:
    print("❌ Error while shuffling:", e)

✅ Data shuffled successfully.

In [8]:
EIS_Shuffled.sample(5)

,LC Factory,LC/SC No,LC/SC Value,LC/SC Quantity,LC/SC Payment Term,Invoice No,Invoice Date,EXP No,EXP Date,Buyer,...,Bank Submit Date,Expected Realize Date,Is FDBC,Bank Name,Shipping Mode,Invoice Status,Realize NO,Realize Date,Realize Value,Is Realize
42574,MGSL,MGSL/H&M-MENS-S.09,4542005.37,1244813,EOM+63,2404511,21-Mar-2024,042/007762/24,21-Mar-2024,H&M,...,30-Apr-2024,NaN,Yes,ABL,Sea,Incentive Pending,DR-05-24-047,08-May-2024,90.60,Yes
10909,MGSL,MGSL/H&M-Mens DBL-S.02,12435079.87,3145397,EOM 63,2505870,24-Apr-2025,00001689-012610-2025,24-Apr-2025,H&M,...,08-Jul-2025,NaN,Yes,DBBL,Sea,Incentive Pending,DR-07-25-014,08-Jul-2025,1620.00,Yes
29973,MGKFL,I55136028,131088.90,23131,21 Days,2407634,21-May-2024,001689-008832-2024,22-May-2024,Benisti Import Export Inc,...,02-Jun-2024,NaN,Yes,DBBL,Sea,Incentive Pending,DR-06-24-034,26-Jun-2024,35015.40,Yes
6540,MGSL,MGSL/H&M-Mens DBL-S.02,12435079.87,3145397,EOM 63,2512399,13-Nov-2025,00001689-029013-2025,13-Nov-2025,H&M,...,18-Jan-2026,20-Jan-2026,Yes,DBBL,Sea,Incentive Pending,DR-01-26-042,18-Jan-2026,211.11,Yes
6837,MGSL,MGSL/H&M-Mens DBL-S.02,12435079.87,3145397,EOM 63,2513997,28-Dec-2025,00001689-033294-2025,28-Dec-2025,H&M,...,NaN,NaN,No,DBBL,Sea,Bank Submit Pending,NaN,NaN,NaN,No

In [9]:
EIS_Shuffled.columns

Index(['LC Factory', 'LC/SC No', 'LC/SC Value', 'LC/SC Quantity',
       'LC/SC Payment Term', 'Invoice No', 'Invoice Date', 'EXP No',
       'EXP Date', 'Buyer', 'PO No', 'Merchandiser', 'Destination No',
       'Invoice Qty', 'Carton Qty', 'Invoice Value', 'Discount', 'Commission',
       'ExfactoryDate', 'Ex Factory No', 'Ex Factory', 'On Board Date',
       'Payment Due Date', 'OnBoardDiff', 'Feeder Vessel No',
       'Mother Vessel No', 'Shipping Bill No', 'Shipping Bill Date', 'BL No',
       'BL Date', 'FCR No', 'FCR Date', 'Bank Ref No', 'Bank Submit Date',
       'Expected Realize Date', 'Is FDBC', 'Bank Name', 'Shipping Mode',
       'Invoice Status', 'Realize NO', 'Realize Date', 'Realize Value',
       'Is Realize'],
      dtype='object')

In [10]:
### Delete unnecessary column

EIS_delete_column = EIS_Shuffled.drop(["PO No", "Discount", "Commission", "Payment Due Date", "OnBoardDiff", "Feeder Vessel No",
       "Mother Vessel No", "FCR No", "FCR Date", "Expected Realize Date"], axis=1)

In [11]:
## Rename Column

EIS = EIS_delete_column.rename(columns={
    'LC Factory': 'Factory',
    'LC/SC No': 'LCSC_No',
    'LC/SC Value': 'LCSC_Value',
    'LC/SC Quantity': 'LCSC_Qty',
    'LC/SC Payment Term': 'Payment_Term',
    'Invoice No': 'Invoice_No',
    'Invoice Date': 'Invoice_Date',
    'EXP No': 'EXP_No',
    'EXP Date': 'EXP_Date',
    'Buyer': 'Buyer',
    'Merchandiser': 'Merchandiser',
    'Destination No': 'Destination',
    'Invoice Qty': 'Invoice_Qty',
    'Carton Qty': 'Carton_Qty',
    'Invoice Value': 'Invoice_Value',
    'ExfactoryDate': 'Ex_Factory_Date',
    'Ex Factory No': 'Ex_Factory_No',
    'Ex Factory': 'Ex_Factory',
    'On Board Date': 'On_Board_Date',
    'Payment Due Date': 'Payment_Due_Date',
    'Shipping Bill No': 'Shipping_Bill_No',
    'Shipping Bill Date': 'Shipping_Bill_Date',
    'BL No': 'BL_No',
    'BL Date': 'BL_Date',
    'Bank Ref No': 'FDBC_No',
    'Bank Submit Date': 'Bank_Submit_Date',
    'Is FDBC': 'Is_FDBC',
    'Bank Name': 'Bank',
    'Shipping Mode': 'Shipping_Mode',
    'Invoice Status': 'Status',
    'Realize NO': 'Realize_No',
    'Realize Date': 'Realize_Date',
    'Realize Value': 'Realize_Value',
    'Is Realize': 'Is_Realize'
});

In [12]:
EIS.head(5)

,Factory,LCSC_No,LCSC_Value,LCSC_Qty,Payment_Term,Invoice_No,Invoice_Date,EXP_No,EXP_Date,Buyer,...,FDBC_No,Bank_Submit_Date,Is_FDBC,Bank,Shipping_Mode,Status,Realize_No,Realize_Date,Realize_Value,Is_Realize
0,MGSL,MGSL/H&M Shirt S.09,2543020.67,480678,EOM+63,2401069,21-Jan-2024,042/001871/24,21-Jan-2024,H&M,...,177/24,20-Feb-2024,Yes,ABL,Sea,Incentive Pending,DR-02-24-031,07-Feb-2024,100.00,Yes
1,MGSL,MGSL/PRINCETON SHIRT-8757 S.09,911882.48,283036,EOM+63,2314203,07-Oct-2023,042/015223/23,07-Oct-2023,H&M,...,FDBC/1023/23,05-Nov-2023,Yes,ABL,Sea,Incentive Pending,DR-11-23-041,05-Nov-2023,126.99,Yes
2,MFSL,DC HK1052329,479803.15,58211,L/C at sight,2315180,25-Oct-2023,2155/006810/23,01-Nov-2023,Street One,...,FDBC/2247/23,08-Nov-2023,Yes,PRM,Sea,Incentive Pending,DR-11-23-015,20-Nov-2023,25840.00,Yes
3,MGL,MG Primark BA WB010,3558741.86,901678,30 Days,2409716,26-Jun-2024,00000947-002107-2024,01-Jul-2024,Primark,...,FDBC-983/24,14-Aug-2024,Yes,NBL,Sea,Incentive Pending,DR-08-24-031,12-Aug-2024,13227.60,Yes
4,MGSL,MGSL/H&M Kids S2,7104090.79,2068406,EOM 63,2600613,11-Jan-2026,00001689-001206-2026,11-Jan-2026,H&M,...,NaN,NaN,No,DBBL,Sea,Bank Submit Pending,NaN,NaN,NaN,No

In [13]:
EIS.head()

,Factory,LCSC_No,LCSC_Value,LCSC_Qty,Payment_Term,Invoice_No,Invoice_Date,EXP_No,EXP_Date,Buyer,...,FDBC_No,Bank_Submit_Date,Is_FDBC,Bank,Shipping_Mode,Status,Realize_No,Realize_Date,Realize_Value,Is_Realize
0,MGSL,MGSL/H&M Shirt S.09,2543020.67,480678,EOM+63,2401069,21-Jan-2024,042/001871/24,21-Jan-2024,H&M,...,177/24,20-Feb-2024,Yes,ABL,Sea,Incentive Pending,DR-02-24-031,07-Feb-2024,100.00,Yes
1,MGSL,MGSL/PRINCETON SHIRT-8757 S.09,911882.48,283036,EOM+63,2314203,07-Oct-2023,042/015223/23,07-Oct-2023,H&M,...,FDBC/1023/23,05-Nov-2023,Yes,ABL,Sea,Incentive Pending,DR-11-23-041,05-Nov-2023,126.99,Yes
2,MFSL,DC HK1052329,479803.15,58211,L/C at sight,2315180,25-Oct-2023,2155/006810/23,01-Nov-2023,Street One,...,FDBC/2247/23,08-Nov-2023,Yes,PRM,Sea,Incentive Pending,DR-11-23-015,20-Nov-2023,25840.00,Yes
3,MGL,MG Primark BA WB010,3558741.86,901678,30 Days,2409716,26-Jun-2024,00000947-002107-2024,01-Jul-2024,Primark,...,FDBC-983/24,14-Aug-2024,Yes,NBL,Sea,Incentive Pending,DR-08-24-031,12-Aug-2024,13227.60,Yes
4,MGSL,MGSL/H&M Kids S2,7104090.79,2068406,EOM 63,2600613,11-Jan-2026,00001689-001206-2026,11-Jan-2026,H&M,...,NaN,NaN,No,DBBL,Sea,Bank Submit Pending,NaN,NaN,NaN,No

In [14]:
EIS.shape

(44173, 33)

In [15]:
#### Clean the dataset
def clean_export_dataset(df):
    df = df.drop_duplicates().reset_index(drop=True)
    df.columns = df.columns.str.strip()
    df = df.apply(lambda x: x.str.strip() if x.dtype == "object" else x)
    df = df.dropna(how='all').dropna(axis=1, how='all')
    return df

EIS = clean_export_dataset(EIS)
EIS.shape

(44173, 33)

In [16]:
### Replace null value with blank

for col in EIS.columns:
    if EIS[col].dtype == "object":
        EIS[col] = EIS[col].fillna("")
    elif "datetime" in str(EIS[col].dtype):
        pass  # keep NaT
    else:
        EIS[col] = EIS[col].fillna(0)
EIS.sample(8)

,Factory,LCSC_No,LCSC_Value,LCSC_Qty,Payment_Term,Invoice_No,Invoice_Date,EXP_No,EXP_Date,Buyer,...,FDBC_No,Bank_Submit_Date,Is_FDBC,Bank,Shipping_Mode,Status,Realize_No,Realize_Date,Realize_Value,Is_Realize
19571,MGSL,MGSL/Women Shirt S.1,1921510.96,393613,EOM+63,2501764,30-Jan-2025,00001689-004007-2025,30-Jan-2025,H&M,...,FDC-1355-25,06-Apr-2025,Yes,DBBL,Sea,Incentive Pending,DR-04-25-037,06-Apr-2025,835.20,Yes
11306,MGSL,MGSL/PRINCETON SHIRT - 8757 S.08,3204657.14,761705,60 Days,2314675,15-Oct-2023,042/015813/23,15-Oct-2023,H&M,...,,,No,ABL,Sea,Bank Submit Pending,,,0.00,No
23530,MGSL,MGSL/H&M-MENS-S.0,7963192.82,1672612,EOM+63,2414292,29-Sep-2024,00000042-018728-2024,29-Sep-2024,H&M,...,FDBC-047-25,15-Jan-2025,Yes,ABL,Sea,Incentive Pending,DR-01-25-042,15-Jan-2025,277.83,Yes
7229,MGSL,MGSL/PRINCETON SHIRT - 8757 S.08,3204657.14,761705,60 Days,2312143,16-Aug-2023,042/011911/23,16-Aug-2023,H&M,...,FDBC/846/23,14-Sep-2023,Yes,ABL,Sea,Incentive Pending,DR-09-23-016,14-Sep-2023,688.54,Yes
36506,MGSL,MGSL/H&M-Mens DBL-S.02,12435079.87,3145397,EOM 63,2513195,11-Dec-2025,00001689-031516-2025,11-Dec-2025,H&M,...,FDC-0635-26,08-Feb-2026,Yes,DBBL,Sea,Incentive Pending,DR-02-26-007,08-Feb-2026,836.00,Yes
24919,MGSL,MGSL/ROBIN OXFORD SHIRT SEASON-9,2038510.93,432934,EOM 63,2317114,29-Nov-2023,042/018592/23,30-Nov-2023,H&M,...,FDBC/037/24,24-Jan-2024,Yes,ABL,Sea,Incentive Pending,DR-01-24-014,08-Jan-2024,5125.50,Yes
683,MGSL,MGSL/WOMEN SHIRT S.0,3305216.33,677927,EOM+63,2411573,04-Aug-2024,00000042-017174-2024,04-Aug-2024,H&M,...,986/24,22-Aug-2024,Yes,ABL,Sea,Incentive Pending,DR-09-24-002,03-Sep-2024,294.41,Yes
38910,MGSL,MGSL/H&M-MENS-S.0,7963192.82,1672612,EOM+63,2406158,25-Apr-2024,0042/010334/2024,25-Apr-2024,H&M,...,,,No,ABL,Sea,Bank Submit Pending,,,0.00,No

In [17]:
import pandas as pd

# Define columns by type
date_columns = [
    "Invoice_Date", "EXP_Date", "Ex_Factory_Date",
    "On_Board_Date", "Payment_Due_Date",
    "Shipping_Bill_Date", "BL_Date",
    "Bank_Submit_Date", "Realize_Date"
]

numeric_columns = [
    "LC/SC Value", "LCSC_Value", "LCSC_Qty", "Invoice_Qty",
    "Carton_Qty", "Invoice_Value", "Realize_Value"
]

text_columns = [
    "Factory", "Buyer", "Merchandiser", "Destination",
    "Payment_Term", "Bank", "Shipping_Mode", "Status",
    "Invoice_No", "EXP_No", "Ex_Factory_No", "Ex_Factory",
    "BL_No", "FDBC_No", "Realize_No"
]

boolean_columns = ["Is_FDBC", "Is_Realize"]

# Convert datatypes
for col in EIS.columns:
    if col in date_columns:
        EIS[col] = pd.to_datetime(EIS[col], errors="coerce")
    elif col in numeric_columns:
        EIS[col] = pd.to_numeric(EIS[col], errors="coerce")
    elif col in boolean_columns:
        EIS[col] = EIS[col].replace({"Yes": 1, "No": 0, "YES": 1, "NO": 0})
    elif col in text_columns:
        EIS[col] = EIS[col].astype(str).str.strip()
        # Fix scientific notation for ID columns
        if col in ["EXP_No", "Invoice_No", "Ex_Factory_No", "BL_No", "Realize_No"]:
            EIS[col] = EIS[col].str.replace(r"\.0$", "", regex=True)
    else:
        pass  # leave any other columns as-is

print(EIS.dtypes)
print("✅ Data types converted successfully.")

Factory                       object
LCSC_No                       object
LCSC_Value                   float64
LCSC_Qty                       int64
Payment_Term                  object
Invoice_No                    object
Invoice_Date          datetime64[ns]
EXP_No                        object
EXP_Date              datetime64[ns]
Buyer                         object
Merchandiser                  object
Destination                   object
Invoice_Qty                    int64
Carton_Qty                   float64
Invoice_Value                float64
Ex_Factory_Date       datetime64[ns]
Ex_Factory_No                 object
Ex_Factory                    object
On_Board_Date         datetime64[ns]
Shipping_Bill_No              object
Shipping_Bill_Date    datetime64[ns]
BL_No                         object
BL_Date               datetime64[ns]
FDBC_No                       object
Bank_Submit_Date      datetime64[ns]
Is_FDBC                        int64
Bank                          object
Shipping_Mode                 object
Status                        object
Realize_No                    object
Realize_Date          datetime64[ns]
Realize_Value                float64
Is_Realize                     int64
dtype: object
✅ Data types converted successfully.

In [18]:
EIS.head(5)

,Factory,LCSC_No,LCSC_Value,LCSC_Qty,Payment_Term,Invoice_No,Invoice_Date,EXP_No,EXP_Date,Buyer,...,FDBC_No,Bank_Submit_Date,Is_FDBC,Bank,Shipping_Mode,Status,Realize_No,Realize_Date,Realize_Value,Is_Realize
0,MGSL,MGSL/H&M Shirt S.09,2543020.67,480678,EOM+63,2401069,2024-01-21,042/001871/24,2024-01-21,H&M,...,177/24,2024-02-20,1,ABL,Sea,Incentive Pending,DR-02-24-031,2024-02-07,100.00,1
1,MGSL,MGSL/PRINCETON SHIRT-8757 S.09,911882.48,283036,EOM+63,2314203,2023-10-07,042/015223/23,2023-10-07,H&M,...,FDBC/1023/23,2023-11-05,1,ABL,Sea,Incentive Pending,DR-11-23-041,2023-11-05,126.99,1
2,MFSL,DC HK1052329,479803.15,58211,L/C at sight,2315180,2023-10-25,2155/006810/23,2023-11-01,Street One,...,FDBC/2247/23,2023-11-08,1,PRM,Sea,Incentive Pending,DR-11-23-015,2023-11-20,25840.00,1
3,MGL,MG Primark BA WB010,3558741.86,901678,30 Days,2409716,2024-06-26,00000947-002107-2024,2024-07-01,Primark,...,FDBC-983/24,2024-08-14,1,NBL,Sea,Incentive Pending,DR-08-24-031,2024-08-12,13227.60,1
4,MGSL,MGSL/H&M Kids S2,7104090.79,2068406,EOM 63,2600613,2026-01-11,00001689-001206-2026,2026-01-11,H&M,...,,NaT,0,DBBL,Sea,Bank Submit Pending,,NaT,0.00,0

In [19]:
EIS.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 44173 entries, 0 to 44172
Data columns (total 33 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Factory             44173 non-null  object
 1   LCSC_No             44173 non-null  object
 2   LCSC_Value          44173 non-null  float64
 3   LCSC_Qty            44173 non-null  int64
 4   Payment_Term        44173 non-null  object
 5   Invoice_No          44173 non-null  object
 6   Invoice_Date        44173 non-null  datetime64[ns]
 7   EXP_No              44173 non-null  object
 8   EXP_Date            44173 non-null  datetime64[ns]
 9   Buyer               44173 non-null  object
 10  Merchandiser        44173 non-null  object
 11  Destination         44173 non-null  object
 12  Invoice_Qty         44173 non-null  int64
 13  Carton_Qty          44173 non-null  float64
 14  Invoice_Value       44173 non-null  float64
 15  Ex_Factory_Date     43948 non-null  datetime64[ns]
 16  Ex_Factory_No       44173 non-null  object
 17  Ex_Factory          44173 non-null  object
 18  On_Board_Date       43545 non-null  datetime64[ns]
 19  Shipping_Bill_No    44173 non-null  object
 20  Shipping_Bill_Date  36420 non-null  datetime64[ns]
 21  BL_No               44173 non-null  object
 22  BL_Date             41663 non-null  datetime64[ns]
 23  FDBC_No             44173 non-null  object
 24  Bank_Submit_Date    40705 non-null  datetime64[ns]
 25  Is_FDBC             44173 non-null  int64
 26  Bank                44173 non-null  object
 27  Shipping_Mode       44173 non-null  object
 28  Status              44173 non-null  object
 29  Realize_No          44173 non-null  object
 30  Realize_Date        40503 non-null  datetime64[ns]
 31  Realize_Value       44173 non-null  float64
 32  Is_Realize          44173 non-null  int64
dtypes: datetime64[ns](8), float64(4), int64(4), object(17)
memory usage: 11.1+ MB

In [20]:
EIS.describe()

,LCSC_Value,LCSC_Qty,Invoice_Date,EXP_Date,Invoice_Qty,Carton_Qty,Invoice_Value,Ex_Factory_Date,On_Board_Date,Shipping_Bill_Date,BL_Date,Bank_Submit_Date,Is_FDBC,Realize_Date,Realize_Value,Is_Realize
count,4.417300e+04,4.417300e+04,44173,44173,44173.000000,44173.000000,44173.000000,43948,43545,36420,41663,40705,44173.000000,40503,44173.000000,44173.000000
mean,6.176627e+06,1.665849e+06,2024-09-15 20:42:56.306793728,2024-09-11 12:42:10.016072960,973.260770,34.884183,4194.967850,2024-09-17 22:49:43.016291840,2024-09-21 01:03:25.607991808,2024-08-29 11:33:02.075782400,2024-09-24 20:54:56.968533248,2024-10-13 13:17:16.796462592,0.921491,2024-10-14 11:37:28.633434624,3785.663670,0.916918
min,7.627500e+02,0.000000e+00,2023-02-08 00:00:00,1998-12-31 00:00:00,2.000000,0.000000,5.700000,1998-12-31 00:00:00,2023-03-08 00:00:00,1900-10-02 00:00:00,2014-03-05 00:00:00,2023-02-08 00:00:00,0.000000,2023-06-07 00:00:00,0.000000,0.000000
25%,2.622975e+06,5.015690e+05,2024-02-03 00:00:00,2024-02-04 00:00:00,61.000000,1.000000,241.570000,2024-02-08 00:00:00,2024-02-11 00:00:00,2024-01-13 00:00:00,2024-02-20 12:00:00,2024-03-20 00:00:00,1.000000,2024-03-06 00:00:00,180.540000,1.000000
50%,4.542005e+06,1.244813e+06,2024-09-12 00:00:00,2024-09-12 00:00:00,175.000000,3.000000,656.880000,2024-09-15 00:00:00,2024-09-18 00:00:00,2024-09-29 00:00:00,2024-09-23 00:00:00,2024-09-30 00:00:00,1.000000,2024-09-30 00:00:00,522.480000,1.000000
75%,1.166402e+07,2.755553e+06,2025-04-10 00:00:00,2025-04-10 00:00:00,663.000000,10.000000,2490.900000,2025-04-10 00:00:00,2025-04-03 00:00:00,2025-03-22 00:00:00,2025-04-02 00:00:00,2025-04-28 00:00:00,1.000000,2025-04-28 00:00:00,2087.400000,1.000000
max,1.347979e+07,9.527500e+06,2026-02-18 00:00:00,2026-06-19 00:00:00,99066.000000,7711.000000,480570.440000,2026-02-18 00:00:00,2026-12-31 00:00:00,2026-02-10 00:00:00,2026-12-30 00:00:00,2026-11-01 00:00:00,1.000000,2026-02-10 00:00:00,480570.220000,1.000000
std,4.291808e+06,1.338073e+06,NaN,NaN,2952.217177,188.917001,13796.810957,NaN,NaN,NaN,NaN,NaN,0.268975,NaN,12913.836127,0.276010

In [24]:
############### Add Category Name ###############
EIS["Category"] = np.where(
    EIS["Factory"].isin(['MFSL','MGKFL']),
    'Sweater',
    'Woven'
)

In [25]:
EIS.sample(5)

,Factory,LCSC_No,LCSC_Value,LCSC_Qty,Payment_Term,Invoice_No,Invoice_Date,EXP_No,EXP_Date,Buyer,...,Bank_Submit_Date,Is_FDBC,Bank,Shipping_Mode,Status,Realize_No,Realize_Date,Realize_Value,Is_Realize,Category
33679,MGSL,MGSL/H&M-Mens DBL-S.02,12435079.87,3145397,EOM 63,2601429,2026-01-27,00001689-003343-2026,2026-02-01,H&M,...,NaT,0,DBBL,Air,Bank Submit Pending,,NaT,0.00,0,Woven
10574,MGSL,MGSL/H&M-Mens DBL-S.02,12435079.87,3145397,EOM 63,2507399,2025-05-29,00001689-016351-2025,2025-05-29,H&M,...,2025-09-09,1,DBBL,Sea,Incentive Pending,DR-09-25-032,2025-09-09,6563.36,1,Woven
10596,MGSL,MGSL/Women Shirt S.2,2995246.39,619756,EOM+63,2504567,2025-03-20,00001689-010034-2025,2025-03-20,H&M,...,2025-05-15,1,DBBL,Sea,Incentive Pending,DR-05-25-031,2025-05-15,654.36,1,Woven
9731,MGSL,MGSL/H&M Shirt S.08,4509235.10,950000,EOM+63,2313918,2023-10-01,042/014816/23,2023-10-01,H&M,...,2023-11-02,1,ABL,Sea,Incentive Pending,DR-11-23-042,2023-11-02,29858.50,1,Woven
19278,MGSL,MGSL/ROBIN OXFORD SHIRT SEASON-9,2038510.93,432934,EOM 63,2316144,2023-11-15,042/017714/23,2023-11-15,H&M,...,2023-12-10,1,ABL,Sea,Incentive Pending,DR-12-23-037,2023-12-10,1388.82,1,Woven

In [30]:
EIS['Category'].value_counts()

Category
Woven      42745
Sweater     1428
Name: count, dtype: int64

In [31]:
Buyer_Payment = pd.read_csv("Data/Buyer_Payment_Chart.csv")

In [32]:
Buyer_Payment

,Sl. No.,Buyer,Export Responsible,Ex-Factory,Days,Onboard,Days.1,B/L Collection,Days.2,Bank Doc Submission,Days.3,Payment Term,Payment Date,Remarks,Payment After Ex-Factory
0,1,Assurer Worldwide,NaN,01-01-2026,7.0,08-01-2026,3.0,11-01-2026,NaN,NaN,NaN,10,21-01-2026,not update,20
1,2,Assurer Worldwide Apparel LLC.,NaN,01-01-2026,7.0,08-01-2026,3.0,11-01-2026,NaN,NaN,NaN,10,21-01-2026,not update,20
2,3,Assurer Worldwide Apparel LLC-FZ,NaN,01-01-2026,7.0,08-01-2026,3.0,11-01-2026,NaN,NaN,NaN,10,21-01-2026,not update,20
3,4,Assurer Worldwide Apparel LLC-FZ,NaN,01-01-2026,7.0,08-01-2026,3.0,11-01-2026,NaN,NaN,NaN,10,21-01-2026,not update,20
4,5,Assurer Worldwide Apparel LLC-FZ,NaN,01-01-2026,7.0,08-01-2026,3.0,11-01-2026,NaN,NaN,NaN,10,21-01-2026,not update,20
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
119,120,Miroglio Fashion,NaN,01-01-2026,7.0,08-01-2026,3.0,11-01-2026,NaN,NaN,NaN,90,11-04-2026,not update,100
120,121,Nittex,Sajjad,01-01-2026,7.0,08-01-2026,3.0,11-01-2026,NaN,NaN,NaN,30,10-02-2026,NaN,40
121,122,NEXT RETAIL LTD,Sajjad,01-01-2026,7.0,08-01-2026,3.0,11-01-2026,NaN,NaN,NaN,30,10-02-2026,NaN,40
122,123,NITEX PTE LTD.,Sajjad,01-01-2026,7.0,08-01-2026,3.0,11-01-2026,NaN,NaN,NaN,30,10-02-2026,NaN,40
123,124,NINGBO FOUR SEASONS FASHION IMP. & EXP. COMPAN...,NaN,01-01-2026,7.0,08-01-2026,3.0,11-01-2026,NaN,NaN,NaN,30,10-02-2026,not update,40

In [36]:
# Merge based on Buyer name
EIS = EIS.merge(
    Buyer_Payment[['Buyer', 'Payment After Ex-Factory']],
    on='Buyer',
    how='left'   # Keep all EIS rows
)
# Rename column
EIS.rename(columns={
    'Payment After Ex-Factory': 'PaymentAfterExFactory'
}, inplace=True)

In [34]:
EIS

,Factory,LCSC_No,LCSC_Value,LCSC_Qty,Payment_Term,Invoice_No,Invoice_Date,EXP_No,EXP_Date,Buyer,...,Is_FDBC,Bank,Shipping_Mode,Status,Realize_No,Realize_Date,Realize_Value,Is_Realize,Category,PaymentAfterExFactory
0,MGSL,MGSL/H&M Shirt S.09,2543020.67,480678,EOM+63,2401069,2024-01-21,042/001871/24,2024-01-21,H&M,...,1,ABL,Sea,Incentive Pending,DR-02-24-031,2024-02-07,100.0000,1,Woven,6.0
1,MGSL,MGSL/PRINCETON SHIRT-8757 S.09,911882.48,283036,EOM+63,2314203,2023-10-07,042/015223/23,2023-10-07,H&M,...,1,ABL,Sea,Incentive Pending,DR-11-23-041,2023-11-05,126.9900,1,Woven,6.0
2,MFSL,DC HK1052329,479803.15,58211,L/C at sight,2315180,2023-10-25,2155/006810/23,2023-11-01,Street One,...,1,PRM,Sea,Incentive Pending,DR-11-23-015,2023-11-20,25840.0000,1,Sweater,20.0
3,MGL,MG Primark BA WB010,3558741.86,901678,30 Days,2409716,2024-06-26,00000947-002107-2024,2024-07-01,Primark,...,1,NBL,Sea,Incentive Pending,DR-08-24-031,2024-08-12,13227.6000,1,Woven,44.0
4,MGSL,MGSL/H&M Kids S2,7104090.79,2068406,EOM 63,2600613,2026-01-11,00001689-001206-2026,2026-01-11,H&M,...,0,DBBL,Sea,Bank Submit Pending,,NaT,0.0000,0,Woven,6.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
44173,MGSL,MGSL/H&M Boys S9,12327213.47,4104494,EOM+63,2316553,2023-11-21,042/018037/23,2023-11-22,H&M,...,1,ABL,Sea,Incentive Pending,DR-06-24-009,2024-03-06,418.2899,1,Woven,6.0
44174,MGSL,MGSL/H&M-MENS -S.07,2948973.12,763766,EOM 63,2402727,2024-02-14,042/004631/24,2024-02-14,H&M,...,1,ABL,Sea,Incentive Pending,DR-03-24-033,2024-03-18,2434.5100,1,Woven,6.0
44175,MGSL,MGSL/H&M-Mens DBL-S.02,12435079.87,3145397,EOM 63,2511526,2025-10-05,00001689-026251-2025,2025-10-05,H&M,...,1,DBBL,Sea,Incentive Pending,DR-01-26-006,2026-01-05,16.7200,1,Woven,6.0
44176,MGSL,MGSL/H&M Shirt S.08,4509235.10,950000,EOM+63,2310937,2023-07-09,042/009526/23,2023-07-09,H&M,...,1,ABL,Sea,Incentive Pending,DR-08-23-015,2023-08-08,120.4200,1,Woven,6.0
44177,MGSL,MGSL/WOMEN SHIRT S.0,3305216.33,677927,EOM+63,2407350,2024-05-18,00000042-012282-2024,2024-05-19,H&M,...,1,ABL,Sea,Incentive Pending,DR-06-24-008,2024-06-06,3130.0000,1,Woven,6.0

In [38]:
EIS['FDBC_No']

0              177/24
1        FDBC/1023/23
2        FDBC/2247/23
3         FDBC-983/24
4
             ...
44183         0308/24
44184    FDBC/0376/24
44185     FDC-0063-26
44186     FDBC-726/23
44187    FDBC-0687/24
Name: FDBC_No, Length: 44188, dtype: object

In [41]:
# Assume EIS is your MAIN dataset
df = EIS.copy()
EIS.columns

Index(['Factory', 'LCSC_No', 'LCSC_Value', 'LCSC_Qty', 'Payment_Term',
       'Invoice_No', 'Invoice_Date', 'EXP_No', 'EXP_Date', 'Buyer',
       'Merchandiser', 'Destination', 'Invoice_Qty', 'Carton_Qty',
       'Invoice_Value', 'Ex_Factory_Date', 'Ex_Factory_No', 'Ex_Factory',
       'On_Board_Date', 'Shipping_Bill_No', 'Shipping_Bill_Date', 'BL_No',
       'BL_Date', 'FDBC_No', 'Bank_Submit_Date', 'Is_FDBC', 'Bank',
       'Shipping_Mode', 'Status', 'Realize_No', 'Realize_Date',
       'Realize_Value', 'Is_Realize', 'Category', 'PaymentAfterExFactory',
       'PaymentAfterExFactory'],
      dtype='object')

In [44]:
import pandas as pd
import numpy as np

# =========================================
# COPY DATA & REMOVE DUPLICATE COLUMNS
# =========================================
df = EIS.copy()
df = df.loc[:, ~df.columns.duplicated()]

# =========================================
# CONVERT DATE COLUMNS
# =========================================
date_cols = [
    'Invoice_Date', 'EXP_Date', 'Ex_Factory_Date',
    'On_Board_Date', 'Bank_Submit_Date', 'Realize_Date'
]

for col in date_cols:
    if col in df.columns:
        df[col] = pd.to_datetime(df[col], errors='coerce')

# =========================================
# CONVERT NUMERIC COLUMNS
# =========================================
df['Invoice_Value'] = pd.to_numeric(df['Invoice_Value'], errors='coerce')
df['PaymentAfterExFactory'] = pd.to_numeric(
    df['PaymentAfterExFactory'], errors='coerce'
)

# =========================================
# REMOVE EMPTY FDBC_No
# =========================================
df = df[df['FDBC_No'].notna()]

# =========================================
# GROUP BY FDBC_No
# =========================================
summary = df.groupby('FDBC_No', as_index=False).agg({

    # First match (XLOOKUP equivalent)
    'Status': 'first',
    'Category': 'first',
    'Buyer': 'first',
    'Factory': 'first',
    'Bank': 'first',
    'Payment_Term': 'first',
    'PaymentAfterExFactory': 'first',

    # Date logic
    'Ex_Factory_Date': 'max',
    'Bank_Submit_Date': 'max',

    # COUNTIF
    'Invoice_No': 'count',

    # SUMIF
    'Invoice_Value': 'sum'
})

# Rename columns properly
summary.rename(columns={
    'Factory': 'Company',
    'Payment_Term': 'PaymentTerm',
    'PaymentAfterExFactory': 'PaymentTermAfterExFactory',
    'Ex_Factory_Date': 'LastExFactoryDate',
    'Bank_Submit_Date': 'LastBankSubmitDate',
    'Invoice_No': 'TotalInvoice',
    'Invoice_Value': 'InvoiceValue'
}, inplace=True)

# =========================================
# IsBankSubmit?
# =========================================
summary['IsBankSubmit'] = np.where(
    summary['LastBankSubmitDate'].notna(),
    'YES',
    'NO'
)

# =========================================
# OnBoardDate Range (MIN + MAX)
# =========================================
onboard = (
    df.groupby('FDBC_No')['On_Board_Date']
      .agg(['min', 'max'])
      .reset_index()
)

summary = summary.merge(onboard, on='FDBC_No', how='left')

summary['OnBoardDate_Range'] = np.where(
    summary['min'].notna(),
    summary['min'].dt.strftime('%d-%b-%Y') +
    " to " +
    summary['max'].dt.strftime('%d-%b-%Y'),
    ""
)

summary.drop(columns=['min', 'max'], inplace=True)

# =========================================
# INVOICES (TEXTJOIN Equivalent)
# =========================================
invoice_list = (
    df.sort_values('Invoice_No')
      .drop_duplicates(['FDBC_No', 'Invoice_No'])
      .groupby('FDBC_No')['Invoice_No']
      .agg(','.join)
      .reset_index(name='INVOICES')
)

summary = summary.merge(invoice_list, on='FDBC_No', how='left')

# =========================================
# IsFDBCRealizable?
# =========================================
summary['PaymentTermAfterExFactory'] = pd.to_numeric(
    summary['PaymentTermAfterExFactory'],
    errors='coerce'
)

today = pd.Timestamp.today()

due_date = (
    summary['LastExFactoryDate'] +
    pd.to_timedelta(summary['PaymentTermAfterExFactory'], unit='D')
)

summary['IsFDBCRealizable'] = np.where(
    summary['PaymentTermAfterExFactory'].notna(),
    np.where(
        today > due_date,
        'NeedRealize',
        'NotYetRealize'
    ),
    ""
)

# =========================================
# FINAL TABLE
# =========================================
FDBC_Summary_Table = summary

print("FDBC Summary Table Created Successfully")

FDBC Summary Table Created Successfully

In [45]:
FDBC_Summary_Table

,FDBC_No,Status,Category,Buyer,Company,Bank,PaymentTerm,PaymentTermAfterExFactory,LastExFactoryDate,LastBankSubmitDate,TotalInvoice,InvoiceValue,IsBankSubmit,OnBoardDate_Range,INVOICES,IsFDBCRealizable
0,,Bank Submit Pending,Woven,H&M,MGSL,DBBL,EOM 63,6.0,2026-02-18,NaT,3468,1.203948e+07,NO,08-Mar-2023 to 31-Dec-2026,"2310019,2310034,2310035,2310096,2310326,231032...",NotYetRealize
1,"$1,610.53",Realize Pending,Woven,Springfield,MGL,EXIM,25 Days,31.0,2023-11-02,2024-03-07,1,1.610530e+03,YES,27-Oct-2023 to 27-Oct-2023,2314794,NeedRealize
2,$115847.87,Realize Pending,Sweater,Hellenic,MFSL,PRM,L/C at sight,40.0,2024-11-18,2024-12-17,1,1.158479e+05,YES,21-Nov-2024 to 21-Nov-2024,2414982,NeedRealize
3,$122722.40,Realize Pending,Sweater,Hellenic,MFSL,PRM,L/C at sight,40.0,2024-10-28,2024-12-15,3,1.227224e+05,YES,01-Nov-2024 to 12-Nov-2024,"2413871,2413872,2415858",NeedRealize
4,$18348.30,Realize Pending,Sweater,Hellenic,MFSL,PRM,At Sight,40.0,2024-10-23,2024-11-13,1,1.834830e+04,YES,19-Oct-2024 to 19-Oct-2024,2415532,NeedRealize
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2260,FDC2404,Incentive Pending,Sweater,5 STAR APPAREL LLC,MGKFL,DBBL,At Sight,27.0,2024-05-27,2024-07-28,1,1.890491e+04,YES,09-Jun-2024 to 09-Jun-2024,2407916,NeedRealize
2261,FDC2627,Incentive Pending,Woven,TMS Fashion (HK) Ltd.,MGSL,DBBL,At Sight,28.0,2025-07-05,2025-07-14,1,4.436800e+03,YES,10-Jul-2025 to 10-Jul-2025,2508394,NeedRealize
2262,FDC2656,Incentive Pending,Sweater,"Michael Kors (USA), Inc.",MGKFL,DBBL,30 Days,47.0,2024-07-27,2024-08-15,1,1.164800e+05,YES,08-Jun-2024 to 08-Jun-2024,2411151,NeedRealize
2263,FDC2688,Realize Pending,Sweater,Auric Sourcing BD,MGKFL,DBBL,At Sight,57.0,2024-08-12,2024-08-15,1,6.764000e+02,YES,15-Aug-2024 to 15-Aug-2024,2411200,NeedRealize
2264,fdbc-00118/26,Incentive Pending,Woven,Best Seller,MGNSL,ABL,45 Days,20.0,2026-01-14,2026-02-09,7,2.958178e+05,YES,23-Jan-2026 to 23-Jan-2026,"2600740,2600741,2600743,2600744,2600745,260074...",NeedRealize

In [47]:
# Export to Excel
output_file = "FDBC_Summary_Table.xlsx"  # You can change the file name/path
FDBC_Summary_Table.to_excel(output_file, index=False)

print(f"FDBC Summary Table successfully saved to {output_file}")

FDBC Summary Table successfully saved to FDBC_Summary_Table.xlsx